### ISSUE TITLE
[ERROR] Error !h command

### ISSUE THREAD

**Issue by Zalatis** [Darqam/Aura_Bot#3]
Error when say !h on the discord chat : 
------------------------------------------------------------------------

/Aura_Bot/commands/help.js:33
        message.author.sendCode('asciidoc',sendOut);
                       ^

TypeError: message.author.sendCode is not a function
    at Object.exports.run (/Aura_Bot/commands/help.js:33:17)
    at Client.module.exports.message (/Aura_Bot/events/message.js:40:13)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (/Aura_Bot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/Aura_Bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:102:65)
    at WebSocketConnection.onPacket (/Aura_Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:331:35)
    at WebSocketConnection.onMessage (/Aura_Bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:22)
    at WebSocketClient.internalOnMessage (/Aura_Bot/node_modules/uws/uws.js:103:17)
    at native.client.group.onMessage (/Aura_Bot/node_modules/uws/uws.js:57:15)

**Comment by Darqam** [comment]
I haven't updated this for D.js V12 (i.e master) yet. I'll get to that in a bit.

In the mean time you can just run `npm install discord.js` in your command prompt to stay on stable (which I have now made default).

**Comment by Darqam** [comment]
Resolved the sendCode issue in latest push, Also removed dependence on d.js master, forgot about that and that was not desired.
